In [ ]:
#Name:Shricharan
#Register Number - 125013036
#Date-27/02/2024
#BIN2023R01 - INTRODUCTION TO DATAMINING & MACHINE LEARNING FOR BIOINFORMATICS
#Exercise6
#Version - 1.0

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
data = pd.read_csv('breast-cancer-wisconsin.csv')
data

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
694              776715                3                        1   
695              841769                2                        1   
696              888820                5                       10   
697              897471                4                        8   
698              897471                4                        8   

      Uniformity of Cell Shape  Marginal Adhesion  \
0                            1                  1   
1                            4                  5   
2                            1                  1   
3                            8                  1   
4                            1                  3   
..                         ...                ...   
694                          1                  1   
695                          1                  1   
696                         10                  3   
697                          6                  4   
698                          8                  5   

     Single Epithelial Cell Size Bare Nuclei  Bland Chromatin  \
0                              2           1                3   
1                              7          10                3   
2                              2           2                3   
3                              3           4                3   
4                              2           1                3   
..                           ...         ...              ...   
694                            3           2                1   
695                            2           1                1   
696                            7           3                8   
697                            3           4               10   
698                            4           5               10   

     Normal Nucleoli  Mitoses  Class  
0                  1        1      2  
1                  2        1      2  
2                  1        1      2  
3                  7        1      2  
4                  1        1      2  
..               ...      ...    ...  
694                1        1      2  
695                1        1      2  
696               10        2      4  
697                6        1      4  
698                4        1      4  

[699 rows x 11 columns]

In [ ]:
import pandas as pd
data = pd.read_csv("breast-cancer-wisconsin.csv")
data.replace('?', np.nan, inplace=True)
data.dropna(inplace=True)

In [ ]:
dataset = pd.read_csv("breast-cancer-wisconsin.csv")

dependent_variable = data.pop("Class")
independent_variables = data

correlations = independent_variables.corrwith(dependent_variable)

threshold = 0.6

significant_variables = correlations[abs(correlations) > threshold].index

selected_data = dataset[significant_variables]

print(significant_variables)

Index(['Clump Thickness', 'Uniformity of Cell Size',
       ' Uniformity of Cell Shape', 'Marginal Adhesion',
       'Single Epithelial Cell Size', 'Bland Chromatin', 'Normal Nucleoli'],
      dtype='object')


<ipython-input-4-cc9fc8e08e54>:6: FutureWarning: The default value of numeric_only in DataFrame.corrwith is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlations = independent_variables.corrwith(dependent_variable)


In [ ]:
selected_data

Clump Thickness  Uniformity of Cell Size   Uniformity of Cell Shape  \
0                  5                        1                          1   
1                  5                        4                          4   
2                  3                        1                          1   
3                  6                        8                          8   
4                  4                        1                          1   
..               ...                      ...                        ...   
694                3                        1                          1   
695                2                        1                          1   
696                5                       10                         10   
697                4                        8                          6   
698                4                        8                          8   

     Marginal Adhesion  Single Epithelial Cell Size  Bland Chromatin  \
0                    1                            2                3   
1                    5                            7                3   
2                    1                            2                3   
3                    1                            3                3   
4                    3                            2                3   
..                 ...                          ...              ...   
694                  1                            3                1   
695                  1                            2                1   
696                  3                            7                8   
697                  4                            3               10   
698                  5                            4               10   

     Normal Nucleoli  
0                  1  
1                  2  
2                  1  
3                  7  
4                  1  
..               ...  
694                1  
695                1  
696               10  
697                6  
698                4  

[699 rows x 7 columns]

In [ ]:
from scipy import stats
min_rows = min(selected_data.shape[0], dependent_variable.shape[0])
selected_data = selected_data[:min_rows]
dependent_variable = dependent_variable[:min_rows]


combined_dataset = np.column_stack((selected_data, dependent_variable))

z_scores_combined = np.abs(stats.zscore(combined_dataset))

threshold = 3

cleaned_dataset = combined_dataset[(z_scores_combined < threshold).all(axis=1)]

cleaned_selected_data = cleaned_dataset[:, :-1]
cleaned_dependent_variable = cleaned_dataset[:, -1]

In [ ]:
cleaned_selected_data

array([[ 5,  1,  1, ...,  2,  3,  1],
       [ 5,  4,  4, ...,  7,  3,  2],
       [ 3,  1,  1, ...,  2,  3,  1],
       ...,
       [10, 10, 10, ...,  5, 10, 10],
       [ 5, 10, 10, ...,  4,  5,  6],
       [ 5,  1,  1, ...,  2,  3,  2]])

In [ ]:
cleaned_dependent_variable

array([2, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 4, 4, 2, 2, 4, 2, 4, 4,
       2, 2, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 4, 4, 4, 4, 4, 4,
       2, 2, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2,
       4, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 4, 4, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 4, 4, 4, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 2, 2, 4, 2, 2, 2,
       2, 4, 4, 2, 4, 2, 4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4,
       2, 2, 4, 2, 4, 4, 2, 4, 2, 2, 4, 4, 2, 2, 2, 2, 4, 4, 2, 2, 2, 2,
       2, 4, 4, 4, 2, 4, 2, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 4, 4, 2, 2, 2,
       2, 2, 2, 2, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 4, 2, 4, 4, 4, 2, 2, 4,
       2, 2, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 4, 2, 4, 4, 4, 2, 2, 2, 2, 4, 4, 4, 4, 2, 4, 4,
       4, 4, 2, 4, 2, 2, 2, 2, 4, 2, 2, 4, 4, 4, 4, 4, 2, 4, 4, 2, 2, 4,
       4, 2, 4, 4, 2, 4, 2, 4, 4, 2, 2, 4, 2, 2, 2, 4, 2, 2, 4, 4, 2, 2,
       4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 4, 4, 2, 4,

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler_standardization = StandardScaler()
selected_data_standardized = scaler_standardization.fit_transform(cleaned_selected_data)
selected_data_standardized

array([[ 0.25009836, -0.66593412, -0.71684742, ..., -0.53081008,
        -0.13550514, -0.58590475],
       [ 0.25009836,  0.38707084,  0.35759975, ...,  2.39717786,
        -0.13550514, -0.2481418 ],
       [-0.47463111, -0.66593412, -0.71684742, ..., -0.53081008,
        -0.13550514, -0.58590475],
       ...,
       [ 2.06192204,  2.49308075,  2.50649407, ...,  1.22598268,
         2.89609015,  2.4539618 ],
       [ 0.25009836,  2.49308075,  2.50649407, ...,  0.64038509,
         0.73066495,  1.10291   ],
       [ 0.25009836, -0.66593412, -0.71684742, ..., -0.53081008,
        -0.13550514, -0.2481418 ]])

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(selected_data_standardized,cleaned_dependent_variable, test_size=0.2, random_state=42)

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (521, 7)
X_test shape: (131, 7)
y_train shape: (521,)
y_test shape: (131,)


In [ ]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [ ]:
y_pred = model.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))

print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.6106870229007634
Classification Report:
              precision    recall  f1-score   support

           2       0.66      0.87      0.75        89
           4       0.20      0.07      0.11        42

    accuracy                           0.61       131
   macro avg       0.43      0.47      0.43       131
weighted avg       0.52      0.61      0.54       131

Confusion Matrix:
[[77 12]
 [39  3]]
